### ISSUE TITLE
variogram grey background

### ISSUE THREAD

**Issue by snstats** [biometryhub/biometryassist#24]
use theme_bw if possible

**Comment by snstats** [comment]
I had a look at this and theme_bw() is there and appears to be working. The grey seems data dependent and I am not sure that we can do any more about is. I tried switching the order of the themes but the order has to be the way it is. Not sure where to go from here.

**Comment by rogerssam** [comment]
Yes, I had a quick look at this too. For some reason the interpolation function is generating `NA` values for the last row or column, which is what's causing those grey edges. I'm not sure how to fix this yet. Also relates to
