### ISSUE TITLE
variogram bug - doesn't handle NA's

### ISSUE THREAD

**Issue by snstats** [biometryhub/biometryassist#25]
![variogram bug](https://user-images.githubusercontent.com/65264926/156674461-3954e17d-1895-44a8-9221-a1a6a9627259.jpg)

**Comment by rogerssam** [comment]
Not sure if this is fixed now that #24 is fixed. @snstats do you have any example cases for this?
I'm not sure how you would get an NA residual either?

**Comment by rogerssam** [comment]
Fixed now
