### ISSUE TITLE
Is there an NA action?

### ISSUE THREAD

**Issue by lsaverbio** [biometryhub/biometryassist#32]
Hi I have NA's in my data and getting an error that 'NA is not allowed'.  Is there a way to say 'include' or 'omit'?

Here is my code if at all helpful:
asreml_Iblock_di <- asreml (fixed = cbind (la_pro, sb_pro) ~ name + year + mat, random = ~rep + Block + rep:Block,
                                       residual = ~id(units):us(trait),
                                       data=e,
                                       family=asr_binomial(link = "logit", dispersion = 1, total = 5),
                                       na.action = na.method(x="include")
                                    )
wald(asreml_Iblock_di, denDF = "default", ssType = "conditional")
pred.asr <- predict(asreml_Iblock_di, classify = "name", sed = TRUE)
pred.out <- mct.out(model.obj = asreml_Iblock_di, pred.obj = pred.asr,
                    classify = "name", order = "descending", decimals = 5, save = TRUE, savename = "predicted_values_05_23.csv")

**Comment by lsaverbio** [comment]
Update:  I removed all NA from my data and still get the error.  This must be more complicated.  

Here is output with the error listed at the end:
Binomial; Logit  Mu=P=1/(1+exp(-XB));                  V=Mu(1-Mu)/N
Note: The LogLik value is unsuitable for comparing GLM models

Deviance from GLM fit:  5056.54
Variance heterogenity factor (Deviance/df):    0.96
(assuming 5288 degrees of freedom)
Binomial; Logit  Mu=P=1/(1+exp(-XB));                  V=Mu(1-Mu)/N
Note: The LogLik value is unsuitable for comparing GLM models

Deviance from GLM fit:  5056.91
Variance heterogenity factor (Deviance/df):    0.96
(assuming 5288 degrees of freedom)
Calculating denominator DF
**Error in vec2mat(x) : 261726 NAs not allowed, found in x**

**Comment by rogerssam** [comment]
Thanks for downloading the new package and checking @lsaverbio. I suspect it's due to the binomial GLMM. We haven't specifically designed biometryassist to handle those cases, but if you were willing to provide me some example data I can investigate supporting GLMMs. You can just upload it to a comment or email it to biometrytraining@adelaide.edu.au.

Out of interest, where did you come across BiometryTraining?

Thanks,
Sam

**Comment by rogerssam** [comment]
No problem, let me know how it goes 🙂

Probably best to make another thread about your other problem.
